openapi: 3.0.0
info:
  title: Paradex WebSocket API
  version: "1.0.0"

servers:
  - url: wss://ws.api.${env}.paradex.trade
    description: Production WebSocket Server
    protocol: wss
    x-fern-server-name: Production

x-fern-base-path: /v1

paths: {}
components: {}