name: Update OpenAPI Specification

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.OPENAPI_SYNC_TOKEN }}
      
      - name: Install Fern CLI
        run: |
          npm install -g fern-api
          echo "$HOME/.fern" >> $GITHUB_PATH

      - name: Run fern upgrade
        run: fern upgrade
      
      - name: Update OpenAPI Spec
        uses: fern-api/sync-openapi@v2
        with:
          token: ${{ secrets.OPENAPI_SYNC_TOKEN }}
          branch: 'update-openapi-spec'
          update_from_source: true
          add_timestamp: true
